module.exports = {
  operation: {
    perform: {
      url:
        'https://api.fiken.no/api/v2/companies/{{bundle.inputData.slug}}/products',
      method: 'GET',
      params: {
        name: '{{bundle.inputData.name}}',
        productNumber: '{{bundle.inputData.productNumber}}',
      },
      headers: { Authorization: 'Bearer {{bundle.authData.access_token}}' },
      removeMissingValuesFrom: { params: true, body: true },
      body: {},
    },
    inputFields: [
      {
        key: 'slug',
        label: 'Company',
        type: 'string',
        helpText: 'Choose Fiken company',
        dynamic: 'get_companies.slug.slug',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'name',
        label: 'Product name',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'productNumber',
        label: 'Product Number',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
    ],
    sample: {
      productId: 2888156,
      createdDate: {},
      lastModifiedDate: {},
      name: 'Spade',
      unitPrice: 300000,
      incomeAccount: 3000,
      vatType: 'high',
      active: true,
      productNumber: '125-1',
      stock: 5,
      note: 'string',
    },
    outputFields: [
      { key: 'productId', label: 'Product ID', type: 'integer' },
      { key: 'name', label: 'Product name' },
      { key: 'unitPrice', type: 'integer', label: 'Unite Price' },
      { key: 'incomeAccount', label: 'Income Account' },
      { key: 'vatType', label: 'VAT Type' },
      { key: 'active', type: 'boolean', label: 'Active?' },
      { key: 'productNumber', label: 'Product Number' },
      { key: 'stock', type: 'integer', label: 'Stock' },
      { key: 'note', label: 'Note' },
    ],
  },
  key: 'find_product',
  noun: 'Product',
  display: {
    label: 'Find product',
    description: 'Find Fiken product',
    hidden: false,
    important: false,
  },
};
