module.exports = {
  operation: {
    perform: {
      url:
        'https://api.fiken.no/api/v2/companies/{{bundle.inputData.slug}}/contacts',
      method: 'GET',
      params: {
        name: '{{bundle.inputData.name}}',
        email: '{{bundle.inputData.email}}',
        organizationNumber: '{{bundle.inputData.organizationNumber}}',
        supplierNumber: '{{bundle.inputData.supplierNumber}}',
        customerNumber: '{{bundle.inputData.customerNumber}}',
        memberNumber: '{{bundle.inputData.memberNumber}}',
        customer: '{{bundle.inputData.customer}}',
        supplier: '{{bundle.inputData.supplier}}',
        inactive: '{{bundle.inputData.inactive}}',
        group: '{{bundle.inputData.group}}',
      },
      headers: { Authorization: 'Bearer {{bundle.authData.access_token}}' },
      body: {},
      removeMissingValuesFrom: { params: true, body: true },
    },
    inputFields: [
      {
        key: 'slug',
        label: 'Company',
        type: 'string',
        helpText: 'Retrieves all contacts for the specified company.',
        dynamic: 'get_companies.slug.slug',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'supplierNumber',
        label: 'Supplier number',
        type: 'integer',
        helpText:
          'Find all results with the supplier number equal to the specified parameter.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'customerNumber',
        label: 'Customer number',
        type: 'integer',
        helpText:
          'Find all results with the customer number equal to the specified parameter.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'memberNumber',
        label: 'Member number',
        type: 'integer',
        helpText:
          'Find all results with the member number equal to the specified parameter.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'name',
        label: 'Name',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'organizationNumber',
        label: 'Organization number',
        type: 'string',
        helpText:
          'Find all results with the organization number equal to the specified parameter.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'email',
        label: 'Email',
        type: 'string',
        helpText:
          'Find all results with the email equal to the specified parameter.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'customer',
        label: 'Is customer',
        type: 'boolean',
        helpText:
          'Returns all contacts that are customers. If filter is set for both supplier and customer = true, only contacts that are both supplier and customer will be returned.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'supplier',
        label: 'Is supplier',
        type: 'boolean',
        helpText:
          'Returns all contacts that are suppliers. If filter is set for both supplier and customer = true, only contacts that are both supplier and customer will be returned.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'inactive',
        label: 'Is inactive',
        type: 'boolean',
        helpText:
          'Return all active contacts (false) or all inactive contacts (true).',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'group',
        label: 'Group',
        type: 'string',
        helpText:
          'Return contacts in contact group, exact match only. Groups are only used for customers, not suppliers.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
    ],
    sample: {
      contactId: 1832181455,
      lastModifiedDate: '2021-01-23',
      name: 'Demokunde',
      customerNumber: 10001,
      customerAccountCode: '1500:10001',
      customer: true,
      supplier: false,
      contactPerson: [],
      language: 'Norwegian',
      inactive: false,
      address: {
        streetAddress: 'Demoveien 22',
        city: 'Oslo',
        postCode: '0190',
        country: 'Norge',
      },
    },
    outputFields: [
      { key: 'contactId', type: 'integer' },
      { key: 'lastModifiedDate' },
      { key: 'name' },
      { key: 'customerNumber', type: 'integer' },
      { key: 'customerAccountCode' },
      { key: 'customer', type: 'boolean' },
      { key: 'supplier', type: 'boolean' },
      { key: 'language' },
      { key: 'inactive', type: 'boolean' },
      { key: 'address__streetAddress' },
      { key: 'address__city' },
      { key: 'address__postCode' },
      { key: 'address__country' },
      { key: 'email', type: 'string' },
      { key: 'organizationNumber', type: 'string' },
      { key: 'phoneNumber', type: 'string' },
      { key: 'memberNumber', type: 'number' },
    ],
  },
  key: 'get_contacts',
  noun: 'Contact',
  display: {
    label: 'Find Contact',
    description: 'Find contacts with the specified name.',
    hidden: false,
    important: true,
  },
};
